theforeman/tool_belt

lib/tool_belt/commands/pulp_repository_updater_command.rb
lib/tool_belt/pulp_repository_updater.rb
lib/tool_belt/systools.rb

allow for beta tag pulp cloning

---

configs/katello_32.yaml
lib/tool_belt/koji_builder.rb

Added puppet certs and bastion to config
Also updated for fedora 24 and other small fixes

Updated for 3.2 release

---

configs/katello_33.yaml
lib/tool_belt/commands/mash_scripts_command.rb
lib/tool_belt/mash_script.rb
lib/tool_belt/mash_scripts_builder.rb
mash_scripts/3.3/katello-3.3-client-fedora24.mash
mash_scripts/3.3/katello-3.3-client-fedora25.mash
mash_scripts/3.3/katello-3.3-client-rhel5.mash
mash_scripts/3.3/katello-3.3-client-rhel6.mash
mash_scripts/3.3/katello-3.3-client-rhel7.mash
mash_scripts/3.3/katello-3.3-rhel7.mash
mash_scripts/3.3/katello-3.3-thirdparty-candlepin-rhel7.mash
mash_scripts/3.3/katello-3.3-thirdparty-pulp-rhel7.mash
tools.rb

Add ability to generate mash scripts

---

Gemfile
lib/tool_belt/commands/branch_command.rb
lib/tool_belt/commands/branch_docs_command.rb
lib/tool_belt/docs_repository.rb
lib/tool_belt/release_environment.rb
lib/tool_belt/repository.rb
tools.rb

[RFC] Add branch and branch-docs commands

---

configs/pulp_2.15.yaml

I am looking to use tool_belt for handling some aspects of Pulp releases. At this time it is unclear what functionality will be used so starting with the basic environment setup for repositories.

Add Pulp 2.15 config

---

configs/katello_37.yaml

This is my first release, so I would appreciate close scrutiny of this.

Add Katello 3.7 config

---

configs/katello_37.yaml

I preemptively bumped puppet-certs. Let me know if we shouldn't do that for some reason

Bumps for Katello 3.7

---

configs/katello_nightly.yaml

Doing this on nightly first then will adjust Katello 3.7

Add Fedora 28, Remove Fedora 26

---

lib/tool_belt/docs_repository.rb

PR to the foreman.org fails checks without this otherwise undocumented bit

Copy Katello sidebar when branching docs

---

configs/katello_37.yaml

Waiting on hammer-cli-katello & puppet-candlepin release. both in flight & preemptively bumped here.

Katello 3.7 config updates

---

configs/katello/3.8.yaml

Add Katello 3.8 configuration

---

configs/bastion/20.yaml
configs/foreman/1.10.yaml
configs/foreman/1.11.yaml
configs/foreman/1.12.yaml
configs/foreman/1.13.yaml
configs/foreman/1.14.yaml
configs/foreman/1.15.yaml
configs/foreman/1.7.yaml
configs/foreman/1.8.yaml
configs/foreman/1.9.yaml
configs/katello/2.1.yaml
configs/katello/2.2.yaml
configs/katello/2.3.yaml
configs/katello/2.4.yaml
configs/katello/3.0.yaml
configs/katello/3.1.yaml
configs/katello/3.2.yaml
configs/katello/3.3.yaml
configs/katello/3.4.yaml
configs/katello/3.5.yaml
configs/katello/3.6.yaml
configs/katello/3.7.yaml
lib/tool_belt/redmine/issue.rb
lib/tool_belt/redmine/project.rb

~Don't merge yet.~ Good to go.
This is the core changes to the code to start the review process. I'm going through the configs to update the release_ids to match the versions in Redmine, will update the PR once they're ready. I've done one Foreman and one Katello file for testing.
@ehelms could you check this works as expected?

Update release_id to fixed_version_id for removal of Backlogs

---

configs/foreman/1.20.yaml
mash_scripts/foreman/1.20.0/foreman-rails-1.20-rhel7.mash

Sets strict keys to true and generates a foreman-rails mash config.

Update 1.20 mash configs

---

configs/katello/3.12.yaml

Add release name and hammer-cli-katello to release

---

configs/katello/3.12.yaml

@jturel this looks like it is already in the docs so adding to ignore list

Update 3.12 ignores

---

configs/katello/3.12.yaml

Bump 3.12 to 3.12.1

---

configs/katello/3.12.yaml

@jturel since we have 2 issues already aligned I updating the config.

Bump Katello 3.12 config to 3.12.2

---

configs/katello/3.12.yaml
configs/katello/3.13.yaml

they had not have the right parents set

correct katello configs

---

configs/katello/3.12.yaml
configs/katello/3.13.yaml

@jturel here is the pr for 3.12.3

Add Katello 3.12.3 release to toolbelt

---

configs/katello/3.13.yaml

This is the config change for 3.13.1, which apparently I didn't push earlier.

Updates config for katello 3.13.1 and 3.13.2.

---

procedures/foreman/branch.md.erb
procedures/foreman/release.md.erb
procedures/katello/branch.md.erb
procedures/katello/release.md.erb

Looks like the checklist plugin sometimes has a hard time handling
`* [ ]` checkboxes.
https://meta.discourse.org/t/checklist-plugin-interactive-checkboxes-made-simple/36362/148
for details.

Change list markdown for checkboxes

---

procedures/foreman/branch.md.erb
procedures/katello/branch.md.erb

and these need to be added to the stable config too

add a note that nightly might got new repos

---

configs/katello/nightly.yaml

Add postgersql 12 scldevel to pulp tag

---

lib/tool_belt/bugzilla.rb
lib/tool_belt/redmine/redmine_resource.rb

Add JSON requires back

---

procedures/katello/release.md.erb

The command has changed since the procedure was written

Update procedure for deprecation warnings

---

configs/katello/3.16.yaml

I've populated this so the changelog can be created.

Populate repos hash for Katello 3.16

---

configs/foreman/2.1.yaml
configs/foreman/nightly.yaml

we need other external repos so that we can build ruby stuff

fix el8 plugin builds

---

procedures/katello/branch.md.erb

The translation steps weren't completely straight-forward so I've laid them out here.

Update Katello translation steps before branching

---

configs/katello/3.16.yaml

also re-arrange inheritance to match 3.15

adjust katello config to properly fetch build groups

---

configs/katello/nightly.yaml
configs/pulpcore/nightly.yaml

it's a build-dependency of ansible-lint
also add test-flat-el8 as that's what is configured in prod
oh, and fix syntax ;)

add ansible-29 repo to pulpcore

---

configs/katello/3.17.yaml
mash_scripts/katello/3.17.0/katello-3.17-rhel7.mash
mash_scripts/katello/3.17.0/katello-3.17-thirdparty-candlepin-rhel7.mash
mash_scripts/katello/3.17.0/katello-pulpcore-3.17-el7.mash

Add Katello 3.17

---

configs/katello/3.17.yaml

@ehelms updated with the prior releases, thanks for helping me locate the error.

Update 3.17 config with prior releases

---

configs/katello/3.17.yaml
procedures/katello/release.md.erb

Also updated the release procedure to make sure we get a release when necessary
cc @ehelms @chris1984

Add foreman_virt_who_configure to Katello 3.17

---

procedures/katello/branch.md.erb

Hit issues with package from yum not working, updated to use pip and added steps on how to install grunt.

Update Transifex in branch docs.

---

procedures/foreman/branch.md.erb

The goal here is to identify as many things that can be either done and merged or a PR staged for prior to branch day.

Move some branch steps to stabliziation week

---

configs/katello/3.16.yaml
configs/katello/3.17.yaml
configs/katello/3.18.yaml

Add 3.16.3 to Katello configs

---

configs/katello/4.0.yaml

#331 discussed the change of hammer version, but I failed to push it :facepalm:

correct katello 4.0 config

---

procedures/foreman/branch.md.erb

Add foreman-documentation branching info

---

procedures/foreman/branch.md.erb

don't update expected version

---

configs/pulpcore/3.15.yaml

add ruby and swig modules to pulpcore buildroot

---

procedures/foreman/branch.md.erb

otherwise hooks are not set up

add step to trigger debian packaging build

---

configs/katello/4.3.yaml

Updated the release number and changed 4.2 to 4.3, not sure what else is needed, so marking as draft.

Add Katello 4.3 to Tool Belt

---

configs/foreman/nightly.yaml

We've stopped building this so there is no more need for this config to exist.

Drop foreman-client-nightly-rhel6

---

configs/katello/4.4.yaml

We need 4.4.0.2 now to add another crucial bugfix: https://projects.theforeman.org/issues/34707

Add Katello 4.4.0.1 and 4.4.0.2

---

procedures/katello/release.md.erb

A reminder to test out the docs before we post a release announcement.

Add note to check install + upgrade before releasing

---

configs/katello/4.6.yaml

Add 4.6 release config

---

configs/katello/4.4.yaml
configs/katello/4.5.yaml

Adds some versions and some ignores.

Update Katello 4.4 and 4.5 configs

---

procedures/foreman/branch.md.erb

Foreman nightly dropped these files.

Remove tito changes from branching docs

---

configs/katello/4.7.yaml

@ekohl when you get a chance, can this get a review please?

Add 4.7 release config

---

procedures/foreman/branch.md.erb
procedures/katello/branch.md.erb
procedures/katello/release.md.erb

See individual commits for details.

Fix various issues with Katello's procedures

---

procedures/katello/branch.md.erb

@ekohl here is the pr to update the command to pull in tx

Update translations procedure on Katello branching docs

---

procedures/foreman/release.md.erb

Fixes: 5ab794c3e1ec3ff882344ac561b28afdd89ba65d

Avoid generating empty lines

---

configs/katello/4.7.yaml

@ekohl here is the toolbelt pr for 4.7.1

Add Katello 4.7.1 to toolbelt

---

configs/katello/4.6.yaml

Update Katello 4.6 config for 4.6.2

---

configs/katello/4.8.yaml
procedures/katello/branch.md.erb

@ekohl here is the 4.8 config with the updated translation steps and version bump that Evgeni wanted.

Add Katello 4.8 and update translation & branch steps

---

procedures/foreman/release.md.erb

This already assumes https://github.com/theforeman/theforeman-rel-eng/pull/200 is merged.

Use wait_packaging script in release process

---

procedures/foreman/branch.md.erb

These were things I noticed while executing branching for Foreman 3.6.

Foreman branching: Move docs branching, add more notes & use script

---

procedures/foreman/branch.md.erb

Depends on https://github.com/theforeman/theforeman-rel-eng/pull/213

Utilize the improved mash scripts in theforeman-rel-eng

---

procedures/foreman/branch.md.erb

Fixes: 200a27bfa7e9c4be6a980a9c15b020f54cda7d20 ("Use upload_yum_gpg script from theforeman-rel-eng")

Correct upload_yum_gpg command URL to match label

---

configs/katello/4.9.yaml
mash_scripts/katello/4.9.0/katello-4.9-el8.mash
mash_scripts/katello/4.9.0/katello-candlepin-4.9-el8.mash

This doesn't add `prior_releases`, but at least allows branching packaging.
@wbclark I decided to open this myself rather than waiting for it. Tomorrow (when I branch) I will need it and last time it not being done at the same time caused problems.

Add Katello 4.9 config

---

procedures/katello/branch.md.erb
procedures/katello/release.md.erb

Must merge with https://github.com/Katello/katello/pull/10574

Add new Katello translation commands for branching

---

procedures/foreman/branch.md.erb

Fixes: 56c9a9fb1d79 ("Use branching scripts in theforeman-rel-eng")

Correct links to develop_branch_{bump,push} scripts

---

procedures/foreman/branch.md.erb
procedures/katello/branch.md.erb
procedures/katello/release.md.erb

These include many notes I found while going through the process. See individual commits for details.

Branching and releasing process improvements

---

configs/katello/4.10.yaml

Adds on to https://github.com/theforeman/tool_belt/pull/555

Add katello 4.10 config

---

configs/foreman/nightly.yaml

Requires https://github.com/theforeman/foreman-infra/pull/1920 first

Use go-toolset 1.20 for Foreman client nightly EL8

---

configs/foreman/nightly.yaml
configs/katello/nightly.yaml

Needs https://github.com/theforeman/foreman-infra/pull/1951

Use NodeJS 14 flat repos

---

configs/katello/4.17.yaml

Add 4.17.1 version to config for 4.17.1 release work.

Add 4.17.1 version to config

---

configs/katello/4.18.yaml

Add config for Katello 4.18
