theforeman/tool_belt

lib/tool_belt/release_environment.rb

Allows the configured repo name and git-generated repo name to differ,
useful when adding the same repo twice for multiple branches under two
names.

Check repos out into the name given in the config file

---

lib/tool_belt/release_environment.rb

When setup-environment is called again, the repos may already exist
with outdated branches.

Pull updates via tracking branch

---

lib/tool_belt/issue_cache.rb

On the first run when no release cache exists, don't call
`release_manifest` as the file read will fail.
lib/ruby/2.0.0/psych.rb:299:in `initialize': No such file or directory - .cache/releases/foreman_1.11.0_issues.yaml (Errno::ENOENT)
from lib/ruby/2.0.0/psych.rb:299:in `open'
from lib/ruby/2.0.0/psych.rb:299:in `load_file'
from tool_belt/lib/tool_belt/issue_cache.rb:69:in `release_manifest'
from tool_belt/lib/tool_belt/issue_cache.rb:48:in `cache_issues'
from tool_belt/lib/tool_belt/issue_cache.rb:27:in `load_issues'
from tool_belt/lib/tool_belt/commands/cherry_pick_command.rb:13:in `execute'

Fix read error when release cache is missing

---

README.md
lib/tool_belt/cherry_picker.rb

The ignores list in configs/ may now be a hash of ticket IDs to a list
of git revisions to permit more precise ignoring. When a ticket contains
multiple revisions from different projects, this prevents each revision
to be ignored without the danger of missing new commits against the
ticket.

Allow ignores list to contain git revisions

---

lib/tool_belt/commands/pulp_repository_updater_command.rb

The 'CommitOption' was renamed to 'ToolsOption' in a prior commit.

Fixing incorrect import

---

lib/tool_belt/pulp_repository_updater.rb

Previous version would update existing packages for clients but not add new
packages.

update to client tagging

---

lib/tool_belt/repository.rb

git.tags is an array, not a hash.  This adds a function to search the
array for the specified tag.

Fix git.tags usage in repository.rb

---

lib/tool_belt/changelog.rb
lib/tool_belt/redmine/issue.rb
lib/tool_belt/redmine/redmine_resource.rb

Specifying --version will only include issues set to that same redmine
release. To generate a complete X.Y changelog, you'd have to run this
command for each Z version.
e.g.
```
./tools.rb changelog --version 3.5.0 configs/katello_35.yaml
./tools.rb changelog --version 3.5.1 configs/katello_35.yaml
./tools.rb changelog --version 3.5.2 configs/katello_35.yaml
```
Default version is the first release (i.e. 3.5.0), which hasn't changed with this PR.

apply --version to changelog output

---

lib/tool_belt/release_environment.rb

```
[jturel@strangeways tool_belt]$ ./tools.rb setup-environment ./configs/katello/3.7.yaml                                                                                                           
/home/jturel/code/tool_belt/lib/tool_belt/release_environment.rb:18:in `mkdir': No such file or directory @ dir_s_mkdir - repos/katello/3.7.0 (Errno::ENOENT)                                  
from /home/jturel/code/tool_belt/lib/tool_belt/release_environment.rb:18:in `setup'                                                                                                       
from /home/jturel/code/tool_belt/lib/tool_belt/commands/setup_environment_command.rb:12:in `execute'                                                                                       
from …
```

Create the release folder

---

configs/foreman/1.21.yaml

This mirrors nightly and avoids the EOL puppet version.

Use puppet5 as an external repo in 1.21

---

configs/foreman/1.20.yaml

We pushed an update into the rails collection that wasn't pushed to 1.20. This matches the koji situation to the way we host it and how we've done it with 1.21.

Introduce a foreman-rails-1.20-rhel7 tag

---

configs/foreman/nightly.yaml

This will need work to actually create this tag before it's merged. I'm also not sure if we should be building with the latest or the oldest supported version.

Move the Foreman nightly build env to Puppet 6

---

procedures/foreman/release.md.erb

I now have scripts to do these steps so the various indivdual steps are no longer needed.
In practice we only sign "extra" RPMs during the RC stage. Usually only on the first but this is good enough.

Update Foreman release procedure

---

configs/foreman/1.22.yaml
configs/foreman/nightly.yaml

When running the script to create the right tags, it fails because it tries to mention a tag that doesn't exist yet. By ordering it, it can succeed.

Move nonscl plugins above scl

---

procedures/katello/branch.md.erb

Fixes this command to copy the contents, not the directory itself, into the target.

Copy dir contents only.

---

lib/tool_belt/commands/changelog_command.rb
lib/tool_belt/commands/cherry_pick_command.rb
lib/tool_belt/issue_service.rb

This PR fixes this scenario:
> As a dev I've released Katello 3.11.1 and want to release 3.11.2 which includes a new prior version: 3.10.2. Cherry-picking works fine, but generating a 3.11.2 changelog does not indicate the changes that were part of 3.10.2
I've achieved this by allowing the ability to map a prior version (3.10.2) to a version within the release stream(3.11.2):
```
:prior_releases:
:3.10.2:
:redmine_version_id: 1037
:3.10.1:
:redmine_version_id: 975
:3.9.2:
:redmine_version_id: 978
:releases:
:3.11.2:
:redmine_version_id: 1038
:prior_releases:
- 3.10.2
:3.11.1:
:redmine_version_id: 992
:3.11.0:
:redmine_version_id: 946
```
This works, but I think it'd like to completely omit the top-level `prior_releases` key and have a `prior_releases` key if relevant for each release in …

Ensure prior releases are reflected in Changelog

---

configs/pulp/2.20.yaml
configs/pulp/2.21.yaml
configs/pulp/2.nightly.yaml

There have been multiple occasions where a Pulp release was pushed but not signed. To mitigate this the pulp mash configs on koji have been updated to enforce strict keys but this hasn't been reflected in the configs until now.

Add GPG keys to pulp configs

---

procedures/foreman/branch.md.erb

0a955d04273dc2d97b5c8b53ff0fa158e1264cb1 changed this, but it doesn't work because obal can't handle packages without sources. This causes the fetch to break and the command quits after the first package.

Fix RPM instructions

---

configs/katello/3.13.yaml

Apparently this config change was left out. As we're producing a 3.13.4 we'll need it.

For katello-3.13.4 release.

---

lib/tool_belt/changelog.rb
test/changelog_test.rb
test/format_entries_test.rb

This PR introduces a check for empty feature sets in a changelog command. If so, then the featueres heading is skipped.

Skip features heading if empty

---

Gemfile
lib/tool_belt/colors.rb
lib/tool_belt/commands/check_deprecation_warnings.rb
lib/tool_belt/deprecation_warning_parser.rb
lib/tool_belt/outdated_deprecation_warning_finder.rb
procedures/katello/release.md.erb
tools.rb

There is a related discussion here:
https://community.theforeman.org/t/deprecation-warnings-how-to-handle-better/17233/9
We will often forget to remove deprecation warnings in the release we say we will. This commit adds the parser gem and a class inheriting from ::Parser::AST::Processor which will scan for deprecation warning methods and any versions in the arguments. It will compare them with the passed in version and print any outdated deprecation locations.

Add deprecation warning scan

---

lib/tool_belt/commands/check_deprecation_warnings.rb
lib/tool_belt/deprecation_warning_parser.rb

Addresses a couple issues I had running `check_deprecation_warnings` locally:
* Improves error messaging if it can't find the repo path.
* Fixes a small bug where it was trying to run a regex `.scan` on something that was expected to be a String, but was not.

check_deprecation_warnings: improve error message

---

configs/foreman/nightly.yaml
configs/katello/nightly.yaml

Some changes that were done to unblock el8 building weren't persisted to tool-belt.
This is updating toolbelt with current koji external repos

Update external repos to reflect current state

---

procedures/foreman/branch.md.erb

During branching there are multiple roles. This adds a heading whether the Release Owner or Release Engineer should perform a task. There is also work for the Installer Maintainer to do module releases.

Assign roles to steps of the branching process

---

configs/katello/3.16.yaml

Updates the hammer-cli-katello and katello-host-tools versions in preparation for Katello 3.16 RC2

Update h-c-k and k-h-t versions for 3.16 RC2

---

lib/tool_belt/commands/procedure.rb
procedures/foreman/branch.md.erb
procedures/foreman/release.md.erb

Adds concrete dates to parts of the tasks, e.g. This mostly works if we always target the same day of the week as the target date, e.g Monday or could adjust for Tuesday. The dates can always be adjusted by hand since this a template.
```
bundle exec ./tools.rb procedure branch foreman 2.2 2020-8-10
```

Add concrete dates to procedures

---

configs/pulpcore/3.9.yaml
mash_scripts/pulpcore/3.9/pulpcore-3.9-el7.mash
mash_scripts/pulpcore/3.9/pulpcore-3.9-el8.mash

gpg needs the last 8, not the first 8…

use correct 8 chars from the 3.9 key

---

configs/katello/3.18.yaml
configs/katello/4.0.yaml

Eventually we're going to update Katello 4.0, 3.18, and 3.17 to pulp-rpm 3.9.  I'm adding 3.17.3 to 3.18 and 4.0 so that issue propagates. (https://projects.theforeman.org/issues/31785)

Add 3.17.3 to prior releases

---

configs/foreman/2.5.yaml
configs/foreman/nightly.yaml
configs/katello/4.1.yaml
configs/katello/nightly.yaml

The flattened Ruby 2.7 repository needs to come before the primary
EL8 flat repository in priority to prevent the base Ruby 2.5 from
being seen as the available Ruby.
I have fixed this in Koji.

Fix flat-ruby27-el8 external repository priority

---

procedures/foreman/branch.md.erb

otherwise the merges to rpm/$release won't trigger builds

trigger packaging release once to setup hooks

---

lib/tool_belt/release_environment.rb

If you try to run `cherry-picks` after adding some repos to your config, and forget to run the `setup-environment` command first, you'll get an error like:
```
Traceback (most recent call last):
11: from ./tools.rb:21:in `<main>'
10: from /home/vagrant/.gem/ruby/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
9: from /home/vagrant/.gem/ruby/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
8: from /home/vagrant/.gem/ruby/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
7: from /home/vagrant/.gem/ruby/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
6: from /home/vagrant/tool_belt/lib/tool_belt/commands/cherry_pick_command.rb:14:in `execute'
5: from /home/vagrant/tool_belt/lib/tool_belt/release_environment.rb:46:in `update_repos'
4: from …
```

Improve error message for 'No such file or directory' error

---

lib/tool_belt/commands/procedure.rb
procedures/foreman/branch.md.erb
procedures/foreman/release.md.erb
procedures/katello/branch.md.erb
procedures/katello/release.md.erb

In Foreman Release there were no explicit roles so those were added.
It also aligns Foreman and Katello naming for the Release Engineer role.
This implements point 1 and 3 as laid out in the [communication RFC](https://community.theforeman.org/t/branching-release-process-communication/23965). The second point is something humans should adopt.
Also includes an unrelated fix to use the tarballs_release script.

Declare explicit roles in procedures

---

procedures/foreman/release.md.erb
procedures/katello/release.md.erb

It is considered good practice to release on a day when there is a working day following it. The risk is that something does break and if you have to wait a whole weekend to fix it, it's bad. Note that goes not only for users but also developers.
This is all not relevant for release candidates. Everyone should be aware that release candidates are not meant for production and the risks associated with them.

Only release on days with a working day after

---

procedures/foreman/release.md.erb

RC1 immediately follows branching. During branching releases have been made so there's no need to create more. This also means we can remove the installer maintainer from the list.

Do not request installer releases for RC1

---

tools.rb

Allows something like the following to now work:
```
./tools.rb koji config/nightly/foreman.yaml --help
```

Allow options and parameters in any order

---

configs/pulpcore/3.15.yaml

don't install non-scl python rpm macros

---

procedures/katello/release.md.erb

The command would cause a x.y.z.rc1 etc... for RC builds.  bump_rpm_packaging sets the prerelease variables appropriately
i.e. this is what caused the katello 4.2.0.rc1-1 vs 4.2.0-0.1.rc1 issue.

Fix katello version bumping step to use bump_rpm_packaging

---

configs/pulpcore/3.15.yaml

we still need to be able to build against 3.6 python

add python36 to pulpcore 3.15

---

configs/katello/4.4.yaml

Here's the new config for Katello 4.4.
Some issues and things I'm not sure about right now:
1) The Foreman 3.2 GPG key isn't available yet
2) I'm not certain I named the tags correctly. They seem to be different from Katello 4.3.  I just based them off of nightly and replaced 'nightly' with the applicable version number.
3) Was it right to increase the version of katello-certs-tools to 2.8.2?

Add config for Katello 4.4

---

procedures/katello/branch.md.erb

In order to better sync-up with Foreman release practices, Katello will wait until branching to create the latest release in redmine.  If, say, Katello 4.5.0 is created in redmine before Katello 4.4.0 has branched, the "fixed in version" field will incorrectly be set by prprocessor to 4.5.0.  To work around this, all future bugs that should be on a version after the latest pre-branched version will be triaged to "Katello Next".
For now, it will be up to the release owner to update Katello Next and related redmine releases at branching time.  The new instructions below illustrate this.
@ekohl wrote up some more detailed notes here: https://community.theforeman.org/t/release-team-meeting-agenda-2022-02-09/27243/3

Add Katello branching procedure steps for Katello Next

---

procedures/katello/branch.md.erb
procedures/katello/release.md.erb

The jenkins-jobs PR for the Foreman-Katello test mapping can be done earlier to put less pressure on branching day.  I also moved the note to review the Foreman schedule up.

Create Katello jenkins-jobs PR and look at Foreman RC date earlier into branching

---

procedures/foreman/release.md.erb

This updates the ERB syntax to split over multiple lines. This is easier to read since there's less interpretation needed.

Update Foreman release procedure formatting

---

configs/foreman/3.3.yaml

I can't see what changed here
```
based_off: foreman-plugins-nigthly-nonscl-rhel7
based_off: foreman-plugins-nightly-nonscl-rhel7
```
But I had to change this

Fix based_off for foreman 3.3

---

lib/tool_belt/koji_tools.rb

sometimes, people delete tags to re-create them, but then
`koji list-groups` returns "nothing" and that confuses the code trying
to split it

be more resilient when there are no groups in koji

---

procedures/foreman/release.md.erb

This further automates the jobs with more scripts. This is incomplete, but comes from https://github.com/theforeman/tool_belt/pull/378#discussion_r653858611. It's separated to its own PR so that PR wasn't held up.

Also use rel-eng scripts to create the release tags

---

procedures/foreman/branch.md.erb

The previous URL returns a 404 now.
The translation status link is also a 404, but I don't know what the replacement is.

Update Transifex announcement URL

---

procedures/foreman/branch.md.erb
procedures/katello/branch.md.erb

This moves specific instructions into the jenkins-jobs repository. Because of that, it's no longer needed to keep two repositories in sync.
The only downside is that you now need to know the Katello version in the Foreman branching procedure.

Rely on the branch-foreman script in jenkins-jobs

---

lib/tool_belt/template.rb
procedures/foreman/release.md.erb

If it fails to render, the filename becomes part of the stack trace. That makes it easier to find out where it failed.
Fixes: 5d85fa5e5171da66475efb3b13940432a1813b13

Fix template syntax & provide ERB filename

---

procedures/foreman/release.md.erb

Without this it just outputs it. Also makes the file name absolete so you can execute it from the root of the repository.

Make the sed command replace master.adoc

---

procedures/foreman/branch.md.erb
procedures/foreman/release.md.erb

These steps are usually ran rather atomically and indivual checkboxes are too much. It still keeps multiple lines because there are multiple scripts.

Remove individual checkboxes for tagging and signing

---

procedures/foreman/release.md.erb

On RC1 it needs to be added to the navigation while on the GA build it needs to be changed from RC to GA while also making Foreman n-2 unsupported.

Add docs navigation updates to the process

---

lib/tool_belt/commands/procedure.rb
procedures/foreman/release.md.erb

Before this we used a lot of checks on the full version, but very often it was checked if it was the first RC or first GA. All other versions are typically the same. This makes it easier to follow along.

Add is_first_rc and is_first_ga context

---

procedures/foreman/release.md.erb

The release notes are generated based on the content of Redmine. By moving the manual updates after closing the Redmine version you're guaranteed that the list of issues is in sync. Otherwise a change could still go in. The titles could still be changes, but there's no way to avoid that.
A hint is added that the optimal time to write is to wait while packaging is building.

Move manual updates to after tagging

---

lib/tool_belt/commands/procedure.rb

This allows calling the script from directories other than the tool_belt root.

Make procedure paths absolute

---

configs/katello/4.7.yaml
configs/katello/4.8.yaml

I noticed that 4.7 had its own releases in the prior releases section, so I fixed it.

Add Katello 4.7.5 to config releases and fix some 4.7 releases

---

configs/foreman/3.7.yaml

Fixes: eebb34baf6ee ("Add Foreman 3.7 config")

Correct build_package_group_source_tag in Foreman 3.7

---

procedures/katello/branch.md.erb
procedures/katello/release.md.erb

The mo-files command used to commit to Git. We're now changing it to only generate the files. In the past, since the mo files are gitignored, that command was a no-op.
I'm also changing the procedure to use tx-update, which runs tx-pull and gives some more information.
Related Katello PR: https://github.com/Katello/katello/pull/10557

Move mo-files command usage to Katello release time

---

procedures/foreman/branch.md.erb
procedures/foreman/release.md.erb
procedures/katello/branch.md.erb
procedures/katello/release.md.erb

There was confusion about the process. Readers were assuming that checking off the checkbox made the post a wiki, but it's only a reminder to do so.

Add a help link to make a post a wiki

---

procedures/foreman/release.md.erb

It is safe to assume the first version is already rc1 and doesn't need updating.

Skip theforeman-rel-eng version update on RC1

---

configs/katello/4.14.yaml

@pcreech here is the 4.14 config

Add config for Katello 4.14

---

configs/katello/4.15.yaml

Config for 4.15 release. Notably katello-host-tools and foreman_virt_who_configure are needing to be released, @chris1984 is working on virt_who, and I'm looking for release help for katello-host-tools within phoenix.

Add tool_belt config for Katello 4.15

---

configs/katello/4.16.yaml

Add config for Katello 4.16, updating repos to the newest version numbers. 
I added 4.15.1 to the prior-releases section; this may need to be removed depending on the release order of the two versions. I'll get in touch with Ian when he returns from Belgium to confirm 4.15.1 is okay.

Add config for Katello 4.16

---

lib/tool_belt/issue_service.rb

The cherry-pick tool was missing commits from z-stream releases because it couldn't properly access the prior-releases configuration from YAML files due to a hyphen/underscore mismatch. This fix enables the tool to correctly load z-stream issues from Redmine and include their commits in cherry-pick suggestions, ensuring that important fixes targeted for prior releases are properly suggested for cherry-picking to the current release.

Fix cherry-pick tool missing z-stream commits
